name: Bug Report
description: Report a bug or issue with the GitHub Environment Vending module
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the issue you're experiencing...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Configure the module with...
        2. Run terraform plan/apply...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened instead?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: What actually happened?
    validations:
      required: true

  - type: input
    id: terraform-version
    attributes:
      label: Terraform Version
      description: What version of Terraform are you using?
      placeholder: "1.9.0"
    validations:
      required: true

  - type: textarea
    id: provider-versions
    attributes:
      label: Provider Versions
      description: What versions of the providers are you using?
      placeholder: |
        - azurerm: 4.8.0
        - github: 6.3.1
        - random: 3.6.3
    validations:
      required: true

  - type: input
    id: operating-system
    attributes:
      label: Operating System
      description: What operating system are you using?
      placeholder: "macOS 14.5, Ubuntu 22.04, Windows 11, etc."
    validations:
      required: true

  - type: textarea
    id: configuration
    attributes:
      label: Configuration
      description: Relevant Terraform configuration (please sanitize sensitive information)
      render: hcl
      placeholder: |
        # Sanitized configuration that reproduces the issue
        module "github_environments" {
          source = "..."
          # ... configuration
        }
    validations:
      required: false

  - type: textarea
    id: yaml-config
    attributes:
      label: YAML Configuration
      description: Relevant GitHub environments YAML configuration (please sanitize sensitive information)
      render: yaml
      placeholder: |
        repositories:
          - repo: example-repo
            environments:
              - name: dev
                # ... configuration
    validations:
      required: false

  - type: textarea
    id: error-output
    attributes:
      label: Error Output
      description: Full error message or output
      render: shell
      placeholder: |
        Error: ...
        
        Full terraform output or error message
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Debug Logs
      description: Any relevant debug logs (set TF_LOG=DEBUG if needed)
      render: shell
      placeholder: |
        Debug logs if available...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: |
        - Is this a regression? (worked before, now broken)
        - Any workarounds you've found?
        - Related issues or discussions?
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided all the requested information
          required: true
        - label: I have sanitized any sensitive information from the configuration
          required: true 