blank_issues_enabled: true
contact_links:
  - name: 🤝 Contributing Guide
    url: https://github.com/HafslundEcoVannkraft/stratus-tf-aca-gh-vending/blob/main/CONTRIBUTING.md
    about: New to contributing? Start here for a gentle introduction!
  
  - name: 💬 Ask a Question
    url: https://github.com/HafslundEcoVannkraft/stratus-tf-aca-gh-vending/discussions
    about: Have a question? Start a discussion - we're here to help!
  
  - name: 🌟 Good First Issues
    url: https://github.com/HafslundEcoVannkraft/stratus-tf-aca-gh-vending/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22
    about: Perfect for newcomers! Find beginner-friendly tasks to get started.
  
  - name: 📚 Full Documentation
    url: https://github.com/HafslundEcoVannkraft/stratus-tf-aca-gh-vending/blob/main/README.md
    about: Complete documentation and setup guides 