name: Feature Request
description: Suggest a new feature or enhancement for the GitHub Environment Vending module
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide as much detail as possible to help us understand your needs.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see.
      placeholder: Describe the feature you'd like to request...
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What use case does it address?
      placeholder: |
        - What problem are you trying to solve?
        - What is the current limitation or gap?
        - How does this impact your workflow?
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: |
        Describe your ideal solution:
        - How should it behave?
        - What configuration options should it have?
        - How should it integrate with existing features?
    validations:
      required: true

  - type: textarea
    id: example-configuration
    attributes:
      label: Example Configuration
      description: Provide an example of how you envision using this feature
      render: hcl
      placeholder: |
        # Example Terraform configuration
        module "github_environments" {
          source = "..."
          
          # New feature configuration
          new_feature_option = "example"
        }
    validations:
      required: false

  - type: textarea
    id: yaml-example
    attributes:
      label: YAML Configuration Example
      description: If applicable, show how this would work in the YAML configuration
      render: yaml
      placeholder: |
        repositories:
          - repo: example-repo
            environments:
              - name: dev
                # New feature configuration
                new_option: value
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative approaches or workarounds?
      placeholder: |
        - What alternatives have you considered?
        - Are there any current workarounds?
        - Why are those alternatives insufficient?
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to your workflow?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Blocking current work
        - Critical - Cannot proceed without this
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Low - Simple configuration change
        - Medium - New functionality, moderate changes
        - High - Significant new feature
        - Unknown - Not sure about implementation complexity
    validations:
      required: false

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific scenarios where this feature would be useful
      placeholder: |
        1. Use case 1: When deploying to multiple environments...
        2. Use case 2: When managing different types of applications...
        3. Use case 3: When integrating with external systems...
    validations:
      required: false

  - type: textarea
    id: impact
    attributes:
      label: Impact Assessment
      description: How would this feature impact existing functionality?
      placeholder: |
        - Would this be a breaking change?
        - How would it affect existing configurations?
        - Are there any compatibility concerns?
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request.
      placeholder: |
        - Links to relevant documentation
        - Screenshots or diagrams
        - Related issues or discussions
        - Industry standards or best practices
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided a clear description of the feature and its benefits
          required: true
        - label: I have considered the impact on existing functionality
          required: true
        - label: I am willing to help test this feature if implemented
          required: false 